# Haibun based BDD testing

name: $(Build.DefinitionName).$(BuildID).$(Rev:.rr)

trigger:
#- main
  branches:
    include:
    - Piepline-creation

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

#- script: |
#   npm run sim-dev3 &
#  displayName: 'sim dev3'

- script: |
    #CI=true npm run test-junit -- --grep @noauth
    npm run test
  displayName: 'Run tests'